exclude_patterns:
- **/*.md
- **/*.svg
- **/*.yml
- **/*.xml
engines:
  checkstyle:
    enabled: true
    checks:
      com.puppycrawl.tools.checkstyle.checks.blocks.NeedBracesCheck:
        enabled: false