version: "2"
plugins:
  checkstyle:
    enabled: true
  pmd:
    enabled: true
  sonar-java:
    enabled: true
engines:
  checkstyle:
    enabled: true
    checks:
      com.puppycrawl.tools.checkstyle.checks.blocks.NeedBracesCheck:
        enabled: false
      # I prefer to have the + sign in the same line
      com.puppycrawl.tools.checkstyle.checks.whitespace.OperatorWrapCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.imports.CustomImportOrderCheck:
        enabled: false
