# https://github.com/paambaati/codeclimate-action#example-with-jacoco
name: Publish Code Coverage

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '**.xml'
      - '**.yml'

jobs:
  generate-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
          uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Restore Maven cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.6.0
        env:
          # Set CC_TEST_REPORTER_ID as secret of your repo
          CC_TEST_REPORTER_ID: ${{secrets.CODECLIMATE_REPORTER}}
          JACOCO_SOURCE_PATH: "${{github.workspace}}/src/main/java"
        with:
          # The report file must be there, otherwise Code Climate won't find it
          coverageCommand: mvn test
          coverageLocations: ${{github.workspace}}/target/site/jacoco/jacoco.xml:jacoco